name: 'generate java code by schema'

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Maven
      uses: aahmed-se/setup-maven@v3
      with:
        maven-version: 3.6.1
    - name: Build with Maven
      run: mvn jsonschema2pojo:generate --file pom.xml
    - name: git add
      run: git add -A
    - name: Commit files
      run: |
        git config --local user.email "453822487@qq.com"
        git config --local user.name "DominikYang"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: DominikYang/java-demo-test
        github_token: ${{ secrets.JAVA_REPO_TOKEN }}




