name: 'push json to java repo'

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone target repo
      run: |
        cd /home/runner/work
        git clone https://github.com/DominikYang/java-demo-test.git
        ls




