name: 'generate java code by schema'

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Maven
      uses: aahmed-se/setup-maven@v3
      with:
        maven-version: 3.6.1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '9.0.4' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - name: Build with Maven
      run: mvn jsonschema2pojo:generate --file pom.xml
    - name: git add
      run: git add -A
    - name: Commit files
      run: |
        git config --local user.email "453822487@qq.com"
        git config --local user.name "DominikYang"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.JAVA_REPO_TOKEN }}




