name: 'push json to java repo'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8.0.242' # The JDK version to make available on the path.
      - name: prepare environment
        run: |
          cd /tmp
          mkdir workdir
          cd workdir
          mkdir output
          cd ..
      - name: clone
        uses: actions/checkout@master
      - name: check
        run: |
          ls -la
          pwd
      - name: generate
        run: java -jar jsonschema2pojo.jar -srcPath=/home/runner/work/json-schema-test/json-schema-test/schema -outPath=/tmp/workdir/output -packageNameVO=com.example.test.vo -packageNameDTO=com.example.test.dto
      - name: change directory
        run: cd /tmp/workdir
      - name: push
        uses: wu-yu-xuan/deploy-github-pages@action
        with:
          personal_token: ${{ secrets.PUSH_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_branch: test
          source_dir: /tmp/workdir/output
          dest_dir: src/main/java





