name: 'push json to java repo'
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setting
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$PUSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com > ~/.ssh/known_hosts
          chmod 700 ~/.ssh && chmod 600 ~/.ssh/*
          git config --global user.email "453822487@qq.com"
          git config --global user.name "Dominikyang"
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '8.0.242' # The JDK version to make available on the path.
      - name: prepare environment
        run: |
          cd /tmp
          mkdir workdir
          cd workdir
          mkdir output
          cd ..
          git clone git@github.com:DominikYang/json-schema-2-pojo.git
          pwd
      - name: clone
        uses: actions/checkout@master
      - name: move jar
        run: mv /tmp/workdir/json-schema-2-pojo/json-schema-2-pojo/jsonschema2pojo.jar .
      - name: generate
        run: java -jar jsonschema2pojo.jar -srcPath=/home/runner/work/json-schema-test/json-schema-test/schema -outPath=/tmp/workdir/output -packageNameVO=com.example.test.vo -packageNameDTO=com.example.test.dto
      - name: change directory
        run: cd /tmp/workdir
      - name: push
        uses: wu-yu-xuan/deploy-github-pages@action
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
          publish_repo: DominikYang/java-demo-test
          publish_branch: master
          source_dir: /tmp/workdir/output
          dest_dir: src/main/java





